In [1]:
import numpy as np

In [2]:
a = np.arange(6)

In [3]:
a2 = a[np.newaxis, :]

In [4]:
a2.shape

(1, 6)

In [5]:
a = np.array([1, 2, 3, 4, 5, 6])

In [6]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [7]:
print(a[0])

[1 2 3 4]


In [8]:
a = np.array([1, 2, 3])

In [9]:
np.zeros(2)

array([0., 0.])

In [10]:
np.ones(2)

array([1., 1.])

In [11]:
np.empty(2) 

array([1., 1.])

In [12]:
np.arange(4)

array([0, 1, 2, 3])

In [13]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [14]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
x = np.ones(2, dtype=np.int64)

In [16]:
x

array([1, 1], dtype=int64)

In [17]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [18]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
a = np.array([1, 2, 3, 4])

In [20]:
b = np.array([5, 6, 7, 8])

In [21]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
x = np.array([[1, 2], [3, 4]])

In [23]:
y = np.array([[5, 6]])

In [24]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [26]:
array_example.ndim

3

In [27]:
array_example.size

24

In [28]:
array_example.shape

(3, 2, 4)

In [29]:
a = np.arange(6)

In [30]:
print(a)

[0 1 2 3 4 5]


In [31]:
b = a.reshape(3, 2)

In [32]:
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [33]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [34]:
a = np.array([1, 2, 3, 4, 5, 6])

In [35]:
a.shape

(6,)

In [36]:
a2 = a[np.newaxis, :]

In [37]:
a2.shape

(1, 6)

In [38]:
row_vector = a[np.newaxis, :]

In [39]:
row_vector.shape

(1, 6)

In [40]:
col_vector = a[:, np.newaxis]

In [41]:
col_vector.shape

(6, 1)

In [42]:
a = np.array([1, 2, 3, 4, 5, 6])

In [43]:
a.shape

(6,)

In [44]:
b = np.expand_dims(a, axis=1)

In [45]:
b.shape

(6, 1)

In [46]:
c = np.expand_dims(a, axis=0)

In [47]:
c.shape

(1, 6)

In [48]:
data = np.array([1, 2, 3])

In [49]:
data[1]

2

In [50]:
data[0:2]

array([1, 2])

In [51]:
data[1:]

array([2, 3])

In [52]:
data[-2:]

array([2, 3])

In [53]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [54]:
print(a[a < 5])

[1 2 3 4]


In [55]:
five_up = (a >= 5)

In [56]:
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [57]:
divisible_by_2 = a[a%2==0]

In [58]:
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [59]:
c = a[(a > 2) & (a < 11)]

In [60]:
print(c)

[ 3  4  5  6  7  8  9 10]


In [61]:
five_up = (a > 5) | (a == 5)

In [64]:
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [65]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [66]:
b = np.nonzero(a < 5)

In [67]:
print(b)

(array([0, 0, 0, 0], dtype=int32), array([0, 1, 2, 3], dtype=int32))


In [68]:
list_of_coordinates= list(zip(b[0], b[1]))

In [70]:
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [71]:
print(a[b])

[1 2 3 4]


In [72]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr1 = a[3:8]

In [74]:
arr1

array([4, 5, 6, 7, 8])

In [75]:
a1 = np.array([[1, 1],
               [2, 2]])

In [76]:
a2 = np.array([[3, 3],
               [4, 4]])

In [77]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [78]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [79]:
x = np.arange(1, 25).reshape(2, 12)

In [80]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [81]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [82]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [121]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [122]:
b1 = a[0, :]

In [123]:
b1

array([1, 2, 3, 4])

In [124]:
b1[0] = 99

In [125]:
b1

array([99,  2,  3,  4])

In [126]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [127]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [128]:
b2= a[0, :].copy()

In [129]:
b2[0] = 99

In [130]:
b2

array([99,  2,  3,  4])

In [131]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [132]:
data = np.array([1, 2])

In [133]:
ones = np.ones(2, dtype=int)

In [134]:
data + ones

array([2, 3])

In [135]:
data - ones

array([0, 1])

In [136]:
data * data

array([1, 4])

In [137]:
data / data

array([1., 1.])

In [138]:
a = np.array([1, 2, 3, 4])

In [139]:
a.sum()

10

In [140]:
b = np.array([[1, 1], [2, 2]])

In [141]:
b.sum(axis=0)

array([3, 3])

In [142]:
b.sum(axis=1)

array([2, 4])

In [143]:
data = np.array([1.0, 2.0])

In [144]:
data * 1.6

array([1.6, 3.2])

In [145]:
data.max()

2.0

In [146]:
data.min()

1.0

In [147]:
data.sum()

3.0

In [148]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [149]:
a.sum()

4.8595784

In [150]:
a.min()

0.05093587

In [151]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [152]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [153]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [154]:
data[0, 1]

2

In [155]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [156]:
data[0:2, 0]

array([1, 3])

In [157]:
data.max()

6

In [158]:
data.min()

1

In [159]:
data.sum()

21

In [160]:
data = np.array([[1, 2], [5, 3], [4, 6]])

In [161]:
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [162]:
data.max(axis=0)

array([5, 6])

In [163]:
data.max(axis=1)

array([2, 5, 6])

In [164]:
data = np.array([[1, 2], [3, 4]])

In [165]:
ones = np.array([[1, 1], [1, 1]])

In [166]:
data + ones

array([[2, 3],
       [4, 5]])

In [167]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [168]:
ones_row = np.array([[1, 1]])

In [169]:
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [170]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [171]:
np.ones(3)

array([1., 1., 1.])

In [172]:
np.zeros(3)

array([0., 0., 0.])

In [173]:
rng = np.random.default_rng()  # the simplest way to generate random numbers

In [174]:
rng.random(3) 

array([0.28050899, 0.28129457, 0.19967439])

In [175]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [176]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [177]:
rng.random((3, 2)) 

array([[0.09017072, 0.03916971],
       [0.54718355, 0.91287165],
       [0.67260499, 0.50176596]])

In [178]:
rng.integers(5, size=(2, 4)) 

array([[0, 0, 1, 0],
       [1, 3, 3, 1]], dtype=int64)

In [179]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [180]:
unique_values = np.unique(a)

In [181]:
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [182]:
unique_values, indices_list = np.unique(a, return_index=True)

In [183]:
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [184]:
unique_values, occurrence_count = np.unique(a, return_counts=True)

In [185]:
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [186]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [187]:
unique_values = np.unique(a_2d)

In [188]:
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [189]:
unique_rows = np.unique(a_2d, axis=0)

In [190]:
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [191]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)

In [192]:
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [193]:
print(indices)

[0 1 2]


In [194]:
print(occurrence_count)

[2 1 1]


In [195]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [196]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [197]:
arr = np.arange(6).reshape((2, 3))

In [198]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [199]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [200]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [201]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [202]:
reversed_arr = np.flip(arr)

In [203]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [204]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [205]:
reversed_arr = np.flip(arr_2d)

In [206]:
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [207]:
reversed_arr_rows = np.flip(arr_2d, axis=0)

In [208]:
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [209]:
reversed_arr_columns = np.flip(arr_2d, axis=1)

In [210]:
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [211]:
arr_2d[1] = np.flip(arr_2d[1])

In [212]:
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [213]:
arr_2d[:,1] = np.flip(arr_2d[:,1])

In [214]:
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [215]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [216]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [217]:
a1 = x.flatten()

In [218]:
a1[0] = 99

In [219]:
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [220]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [222]:
a2 = x.ravel()

In [223]:
a2[0] = 98

In [224]:
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [225]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
